import React, { useContext, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import NavBar from '../components/NavBar';

const ViewReport = () => {
  const { id } = useParams();
  const { authFetch } = useContext(AuthContext);
  const [report, setReport] = useState(null);
  const [lang, setLang] = useState('english');
  const [showFull, setShowFull] = useState(false);

  useEffect(() => {
    const load = async () => {
      const res = await authFetch('/users/reports');
      const data = await res.json();
      const r = data.reports.find(r => r.file._id === id);
      setReport(r);
    };
    load();
  }, [id, authFetch]);

  if (!report) return <div className="p-6">Loading...</div>;

  const insight = report.insight;

  return (
    <div>
      <NavBar />
      <div className="p-6">
      <h1 className="text-2xl font-bold mb-4">Report</h1>
      <a href={report.file.fileUrl} target="_blank" rel="noreferrer" className="text-blue-600">Open File</a>
      <div className="mt-4">
        <h2 className="text-lg font-semibold">File Preview</h2>
        <div className="mb-4">
          {report.file.fileType && report.file.fileType.toLowerCase() === 'pdf' ? (
            <iframe src={report.file.fileUrl} title="report-pdf" width="100%" height={600} />
          ) : (
            <img src={report.file.fileUrl} alt="report" className="max-w-full h-auto" />
          )}
        </div>
        <button onClick={() => setLang('english')} className="mr-2">English</button>
        <button onClick={() => setLang('roman')} >Roman Urdu</button>
      </div>

      <div className="mt-4">
        <h2 className="text-lg font-semibold">Summary</h2>
        <p className="font-semibold">{insight?.summary || (lang === 'english' ? insight?.englishSummary : insight?.romanUrduSummary) || 'No analysis available yet.'}</p>
        <div className="mt-2">
          <button onClick={() => setShowFull(s => !s)} className="btn mr-2">{showFull ? 'Hide full answer' : 'Show full answer'}</button>
        </div>
        {showFull && (
          <div className="mt-3 p-3 bg-gray-50 rounded">
            <p>{lang === 'english' ? (insight?.fullAnswerEnglish || insight?.englishSummary) : (insight?.fullAnswerRoman || insight?.romanUrduSummary) || 'No detailed answer available.'}</p>
          </div>
        )}

        {/* English Analysis */}
        <div className="mt-4">
          <h3 className="text-md font-semibold">English Analysis</h3>
          <div className="mt-2 p-3 bg-white border rounded">
            <p className="mb-2 font-medium">Short:</p>
            <p>{insight?.englishSummary || 'No English summary available.'}</p>
            <div className="mt-3">
              <p className="mb-1 font-medium">AI Response:</p>
              <p>{insight?.fullAnswerEnglish || 'No detailed English response available.'}</p>
            </div>
          </div>
        </div>

        {/* Roman Urdu Analysis */}
        <div className="mt-4">
          <h3 className="text-md font-semibold">Roman Urdu Analysis</h3>
          <div className="mt-2 p-3 bg-white border rounded">
            <p className="mb-2 font-medium">Short:</p>
            <p>{insight?.romanUrduSummary || 'No Roman Urdu summary available.'}</p>
            <div className="mt-3">
              <p className="mb-1 font-medium">AI Response (Roman):</p>
              <p>{insight?.fullAnswerRoman || 'No detailed Roman Urdu response available.'}</p>
            </div>
          </div>
        </div>

        <h3 className="text-md font-semibold mt-3">Doctor Questions</h3>
        <div className="mt-2">
          {insight?.doctorQuestions?.length ? (
            <ul className="list-disc pl-5">
              {insight.doctorQuestions.map((q, i) => (
                <li key={i} className="mb-2">
                  <div className="font-medium">Q: {q}</div>
                  {/* If doctorAnswers exists (array), show matching answer; otherwise show the AI full answer as a helpful response */}
                  <div className="mt-1 pl-3 text-gray-700">A: {insight?.doctorAnswers?.[i] || (lang === 'english' ? insight?.fullAnswerEnglish : insight?.fullAnswerRoman) || 'No AI response available for this question.'}</div>
                </li>
              ))}
            </ul>
          ) : (
            <div className="text-sm text-gray-600">No questions generated by AI.</div>
          )}
        </div>

        <h3 className="text-md font-semibold mt-3">Highlights</h3>
        <ul>{insight?.highlights?.map((h, i) => <li key={i}>{h}</li>)}</ul>

        <h3 className="text-md font-semibold mt-3">Diet Tips</h3>
        <ul>{insight?.dietTips?.map((d, i) => <li key={i}>{d}</li>)}</ul>

        <h3 className="text-md font-semibold mt-3">Home Remedies</h3>
        <ul>{insight?.homeRemedies?.map((h, i) => <li key={i}>{h}</li>)}</ul>

        <div className="mt-4 text-sm text-gray-600">
          <strong>Disclaimer:</strong> {insight?.disclaimer || 'AI is for understanding only, not for medical advice.'} <br />
          <em>{insight?.disclaimer ? '' : 'Yeh AI sirf samajhne ke liye hai, ilaaj ke liye nahi.'}</em>
        </div>
      </div>
      </div>
    </div>
  );
};

export default ViewReport;
